# Generated by Django 2.1.12 on 2020-03-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useranswer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Answer')),
            ],
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='choice',
            name='user_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.UserAnswer'),
        ),
    ]
