# Generated by Django 2.1.12 on 2020-03-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200304_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='user_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.UserAnswer'),
        ),
    ]
