# Generated by Django 3.0.10 on 2021-01-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210121_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
