# Generated by Django 3.0.10 on 2021-01-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210122_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionversion',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
