# Generated by Django 3.0.10 on 2021-01-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210122_1510'),
        ('core', '0011_auto_20210122_1408'),
    ]

    operations = [
    ]
