# Generated by Django 3.0.10 on 2021-02-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_mptt_upgrade'),
        ('core', '0013_auto_20210129_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionversion',
            name='categories',
        ),
        migrations.AddField(
            model_name='questionversion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.Article'),
        ),
    ]
