# Generated by Django 3.0.10 on 2021-02-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210204_1501'),
        ('core', '0012_useranswer_answer'),
    ]

    operations = [
    ]
