# Generated by Django 3.1.6 on 2021-02-26 09:31

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerversion',
            name='question_version',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='core.questionversion'),
        ),
        migrations.AlterField(
            model_name='questionversion',
            name='question',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='core.question'),
        ),
    ]
