# Generated by Django 3.1.6 on 2021-02-26 15:43

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210226_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerversion',
            name='question_version',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.questionversion'),
        ),
        migrations.AlterField(
            model_name='questionversion',
            name='question',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.question'),
        ),
    ]
