# Generated by Django 3.1.8 on 2021-05-20 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210331_1300'),
        ('core', '0019_auto_20210226_1643'),
    ]

    operations = [
    ]
