# Generated by Django 3.1.7 on 2021-04-22 12:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210422_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('flipcard', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(required=True)), ('frontside', wagtail.core.blocks.RichTextBlock()), ('backside', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
