# Generated by Django 3.1.7 on 2021-04-22 13:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210422_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Flipcard Page', 'verbose_name_plural': 'Flipcard Pages'},
        ),
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('flipcard', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(blank=True, null=True)), ('frontside', wagtail.core.blocks.RichTextBlock()), ('backside', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
