# Generated by Django 3.1.7 on 2021-04-22 13:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('news', '0001_initial'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0024_auto_20210422_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlexPage',
            new_name='FlipcardPage',
        ),
    ]
