# Generated by Django 3.1.7 on 2021-04-22 13:08

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210422_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipcardpage',
            name='content',
            field=wagtail.core.fields.StreamField([('flipcard', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(required=False)), ('frontside', wagtail.core.blocks.RichTextBlock()), ('backside', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
