# Generated by Django 3.1.10 on 2021-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_mptt_upgrade'),
        ('core', '0026_auto_20210422_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionversion',
            name='categories',
            field=models.ManyToManyField(blank=True, to='wiki.Article'),
        ),
    ]
