# Generated by Django 3.0.10 on 2020-09-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsNewsletterPage',
            fields=[
                ('websitepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.WebsitePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.websitepage',),
        ),
    ]
