# Generated by Django 3.0.10 on 2020-09-15 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0052_pagelogentry'),
        ('pages', '0003_newsevaluationindexpage_newsevaluationpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('lecture', 'Vorlesung'), ('exercise', 'Übung'), ('study_group', 'Arbeitsgemeinschaft'), ('exam_prep', 'Klausurenkurs'), ('seminar', 'Seminar')], default='lecture', max_length=255)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('speaker_description', wagtail.core.fields.RichTextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessions',
            },
        ),
    ]
