# Generated by Django 3.0.10 on 2020-09-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_sessionindexpage_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='assessment',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='semester',
            field=models.CharField(blank=True, choices=[('ss2022', 'Sommersemester 2022'), ('ws2022', 'Wintersemester 2022'), ('ss2021', 'Sommersemester 2021'), ('ws2021', 'Wintersemester 2021'), ('ss2020', 'Sommersemester 2020'), ('ws2020', 'Wintersemester 2020'), ('ss2019', 'Sommersemester 2019'), ('ws2019', 'Wintersemester 2019'), ('ss2018', 'Sommersemester 2018'), ('ws2018', 'Wintersemester 2018')], default='ws2020', max_length=255),
        ),
    ]
