# Generated by Django 3.0.10 on 2020-09-15 17:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200915_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='assessment',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='date',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='location',
            field=wagtail.core.fields.RichTextField(blank=True, default='test'),
            preserve_default=False,
        ),
    ]
