# Generated by Django 3.0.10 on 2020-09-16 15:53

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200915_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepage',
            name='sidebar',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
