# Generated by Django 3.0.10 on 2020-09-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_sidebarpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitepagesidebarplacement',
            name='page',
        ),
        migrations.RemoveField(
            model_name='websitepagesidebarplacement',
            name='sidebar',
        ),
        migrations.DeleteModel(
            name='Sidebar',
        ),
        migrations.DeleteModel(
            name='WebsitePageSidebarPlacement',
        ),
    ]
