# Generated by Django 3.0.10 on 2020-09-17 17:35

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_newsindex_newsitem_newsitemrevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarpage',
            name='content',
            field=wagtail.core.fields.StreamField([('column_2_1', wagtail.core.blocks.StructBlock([('column_0', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())])), ('column_1', wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.CharBlock())]))], grid_width=12, group='Columns', template='blocks/columnsblock.html'))]),
        ),
    ]
