# Generated by Django 3.0.10 on 2020-09-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0052_pagelogentry'),
        ('pages', '0011_auto_20200917_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='newsindex',
        ),
        migrations.RemoveField(
            model_name='newsitemrevision',
            name='newsitem',
        ),
        migrations.RemoveField(
            model_name='newsitemrevision',
            name='user',
        ),
        migrations.DeleteModel(
            name='NewsIndex',
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
        migrations.DeleteModel(
            name='NewsItemRevision',
        ),
    ]
