# Generated by Django 3.0.10 on 2020-09-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpolls', '0003_auto_20170511_1620'),
        ('pages', '0015_auto_20200923_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarpage',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailpolls.Poll'),
        ),
    ]
