# Generated by Django 3.0.10 on 2020-09-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_sidebarpage_poll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
        migrations.AlterModelOptions(
            name='sessions',
            options={'verbose_name': 'Lehrveranstaltung'},
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mailadresse'),
        ),
        migrations.AlterField(
            model_name='people',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='people',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='people',
            name='room',
            field=models.CharField(blank=True, max_length=255, verbose_name='Raumnummer'),
        ),
        migrations.AlterField(
            model_name='people',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telefonnummer'),
        ),
    ]
