# Generated by Django 3.0.10 on 2020-10-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20200928_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarpage',
            name='cover_caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
