# Generated by Django 3.1.2 on 2020-10-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20201006_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
