# Generated by Django 3.1.8 on 2021-04-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20210419_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='posterimage',
            new_name='poster_image',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='posterpdf',
            new_name='poster_pdf',
        ),
    ]
