# Generated by Django 3.1.8 on 2021-04-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('news', '0001_initial'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('pages', '0030_events_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='exams',
            options={'verbose_name': 'Klausur', 'verbose_name_plural': 'Klausuren'},
        ),
        migrations.AlterModelOptions(
            name='sessions',
            options={'verbose_name': 'Lehrveranstaltung', 'verbose_name_plural': 'Lehrveranstaltungen'},
        ),
        migrations.AlterField(
            model_name='events',
            name='semester',
            field=models.CharField(blank=True, choices=[('2024_2', 'Wintersemester 2024/2025'), ('2024_1', 'Sommersemester 2024'), ('2023_2', 'Wintersemester 2023/2024'), ('2023_1', 'Sommersemester 2023'), ('2022_2', 'Wintersemester 2022/2023'), ('2022_1', 'Sommersemester 2022'), ('2021_2', 'Wintersemester 2021/2022'), ('2021_1', 'Sommersemester 2021'), ('2020_2', 'Wintersemester 2020/2021'), ('2020_1', 'Sommersemester 2020'), ('2019_2', 'Wintersemester 2019/2020'), ('2019_1', 'Sommersemester 2019'), ('2018_2', 'Wintersemester 2018/2019'), ('2018_1', 'Sommersemester 2018'), ('2017_2', 'Wintersemester 2017/2018'), ('2017_1', 'Sommersemester 2017'), ('2016_2', 'Wintersemester 2016/2017'), ('2016_1', 'Sommersemester 2016'), ('2015_2', 'Wintersemester 2015/2016'), ('2015_1', 'Sommersemester 2015'), ('2014_2', 'Wintersemester 2014/2015'), ('2014_1', 'Sommersemester 2014'), ('2013_2', 'Wintersemester 2013/2014'), ('2013_1', 'Sommersemester 2013'), ('2012_2', 'Wintersemester 2012/2013'), ('2012_1', 'Sommersemester 2012'), ('2011_2', 'Wintersemester 2011/2012'), ('2011_1', 'Sommersemester 2011'), ('2010_2', 'Wintersemester 2010/2011'), ('2010_1', 'Sommersemester 2010')], default='ss2021', max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='EventsIndexPage',
        ),
    ]
