# Generated by Django 3.1.8 on 2021-04-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20210421_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='showmap',
            field=models.BooleanField(default=False),
        ),
    ]
