# Generated by Django 3.1.8 on 2021-05-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('news', '0002_newsindex_content'),
        ('pages', '0033_basepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasePage',
        ),
    ]
