# Generated by Django 3.1.8 on 2021-05-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210521_1354'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('pages', '0034_delete_basepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticlepage',
            name='websitepage_ptr',
        ),
        migrations.RemoveField(
            model_name='newsevaluationindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='newsevaluationpage',
            name='websitepage_ptr',
        ),
        migrations.RemoveField(
            model_name='newsnewsletterpage',
            name='websitepage_ptr',
        ),
        migrations.RemoveField(
            model_name='sidebarpage',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='sidebarpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='sidebarpage',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='websiteindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='websitepage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='websitepagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='websitepagegalleryimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='websitepagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='websitepagetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='wikiindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='wikipage',
            name='node',
        ),
        migrations.RemoveField(
            model_name='wikipage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='NewsArticleIndexPage',
        ),
        migrations.DeleteModel(
            name='NewsArticlePage',
        ),
        migrations.DeleteModel(
            name='NewsEvaluationIndexPage',
        ),
        migrations.DeleteModel(
            name='NewsEvaluationPage',
        ),
        migrations.DeleteModel(
            name='NewsNewsletterPage',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='SidebarPage',
        ),
        migrations.DeleteModel(
            name='WebsiteIndexPage',
        ),
        migrations.DeleteModel(
            name='WebsitePage',
        ),
        migrations.DeleteModel(
            name='WebsitePageGalleryImage',
        ),
        migrations.DeleteModel(
            name='WebsitePageTag',
        ),
        migrations.DeleteModel(
            name='WikiIndexPage',
        ),
        migrations.DeleteModel(
            name='WikiPage',
        ),
    ]
